#!/usr/bin/env python3
"""Merge out/*.json into docs/BENCHMARKS.md. Missing input -> NOT MEASURED. Never writes an unmeasured number."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
DOC = os.path.join(HERE, "..", "..", "docs", "BENCHMARKS.md")

def load(name):
    p = os.path.join(OUT, name)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None

def row(*c): return "| " + " | ".join(str(x) for x in c) + " |"
L = ["# BENCHMARKS (generated by validation/iqoo_bench/make_report.py)", "",
     "Every number below was computed by a script. `NOT MEASURED` means the input was not provided yet.", ""]

asr = load("asr.json")
L += ["## ASR word/char error rate (real recorded clips)", ""]
if asr and asr.get("status") == "MEASURED":
    L += [row("Language", "Clips", "WER", "CER"), row("---", "---", "---", "---")]
    for k, v in asr["per_language"].items(): L.append(row(k, v["clips"], v["WER"], v["CER"]))
else: L.append("NOT MEASURED (record 30 clips, fill asr_clips/manifest.csv and hypotheses.json)")

h = load("heldout.json")
L += ["", "## Fact extraction on held-out cases (written after rules were frozen)", ""]
if h and h.get("status") == "MEASURED":
    L += [row("Language", "Cases", "Precision", "Recall", "F1"), row("---", "---", "---", "---", "---")]
    for k, v in h["per_language"].items(): L.append(row(k, v["cases"], v["precision"], v["recall"], v["f1"]))
else: L.append("NOT MEASURED (only EXAMPLE cases present). The 99.39% precision in older docs is in-sample on self-authored synthetic cases and is not a held-out result.")

f = load("fabrication.json")
L += ["", "## Evidence gate: fabrication rate", ""]
if f:
    L += [row("Metric", "Value"), row("---", "---"), row("Mode", f["status"]), row("Transcripts", f["transcripts"]),
          row("Raw (stub) fabrication rate", f["rawFabricationRate"]), row("After gate", f["gatedFabricationRate"]), "", f"> {f['caveat']}"]
else: L.append("NOT MEASURED")

ln = load("latency_node.json")
L += ["", "## Pipeline latency (rules + grounding + SOAP)", ""]
if ln:
    L += [f"Device: {ln['device']} ({ln['runs']} runs)", "", row("Stage", "p50 ms", "p95 ms"), row("---", "---", "---")]
    for k, v in ln["stages"].items(): L.append(row(k, v["p50"], v["p95"]))
else: L.append("NOT MEASURED")
lp = load("latency_phone.json")
L += ["", "### On the phone", "", "NOT MEASURED (open the app with ?bench=1 on the loaner phone, download the JSON, save as out/latency_phone.json)" if not lp else json.dumps(lp, indent=2)]

L += ["", "## Hardware (Finale, loaner phone)", "", row("Metric", "Status"), row("---", "---"),
      row("NPU vs CPU tokens/s", "NOT MEASURED"), row("Time to first token", "NOT MEASURED"),
      row("Battery % per 10 min", "NOT MEASURED"), row("Temperature after 10 min", "NOT MEASURED"),
      row("Bytes uploaded in airplane mode", "measured live by networkGuard (Device Proof panel); screenshot it")]
os.makedirs(os.path.dirname(DOC), exist_ok=True)
open(DOC, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote", os.path.relpath(DOC))
